name: Resume Pipeline

on:
  push:
    tags:
      - v** # Trigger on every tag push

jobs:
  resume-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3 # this checks out the repo in the ubuntu container
        with:
          fetch-depth: '0'

      - name: "Get latest Tag"
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: "Create resume docs"
        run: |
          make convert

      - name: "Create release"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./output/resume-${{ github.ref_name }}.md
            ./output/resume-${{ github.ref_name }}.pdf
            ./output/resume-${{ github.ref_name }}.html
            ./output/resume-${{ github.ref_name }}.docx
